JOML-CI/JOML

src/org/joml/AngleAxis4f.java
src/org/joml/Quaternion.java
src/org/joml/QuaternionD.java
test/org/joml/test/QuaternionDTest.java
test/org/joml/test/QuaternionTest.java
test/org/joml/test/TestUtil.java
test/org/joml/test/Vector3fTest.java

The quaternion `mul` methods were giving wrong results, so I reimplemented them. I used the formulas from the [Wikipedia quaternion page](https://en.wikipedia.org/wiki/Quaternion#Hamilton_product) for checking.

Quaternion multiplication

---

src/org/joml/Matrix3d.java
src/org/joml/Matrix3f.java
src/org/joml/Matrix4d.java
src/org/joml/Matrix4f.java

Added Row Accessors for Matrix classes.

Row Accessors for Matrix classes.

---

README.md

Adds a section about JogAmp JOGL 2 into README.md to ease the use of JOML with this set of OpenGL & OpenGL-ES bindings.

Adds a section about JOGL into README.md

---

README.md

"The count argument indicates the number of matrices to be passed" opengl.org/sdk/docs/man/html/glUniform.xhtml

Wrong parameter passed to glUniformMatrix4fv

---

src/org/joml/Matrix3d.java
src/org/joml/Matrix3f.java
src/org/joml/Matrix4d.java
src/org/joml/Matrix4f.java
src/org/joml/Quaterniond.java
src/org/joml/Quaternionf.java
src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java

Reference to #43 
I looked over the javadoc very carefully... please tell me about any stupidities I overlooked :smile:

All getters now return the object that is modified.

---

src/org/joml/Vector2i.java
src/org/joml/Vector2ic.java
src/org/joml/Vector3i.java
src/org/joml/Vector3ic.java
src/org/joml/Vector4i.java
src/org/joml/Vector4ic.java

implemented methods for the Manhatten distance for integer types. not sure if it would benefit for float or double types but this is pretty useful for integer types when comparing distances.

implemented grid distance

---

src/org/joml/Vector2d.java

The current Vector2d.sub(Vector2f) doesn't subtract, but add the values. I change it to subtract.

Fix Vector2d subtraction with Vector2f

---

src/org/joml/internal/MemUtil.java

Fix several cases of 4 bytes offsets with doubles in MemUtil (#181)

---

src/org/joml/Extensions.kt
src/org/joml/Matrix2d.java
src/org/joml/Matrix2dc.java
src/org/joml/Matrix2f.java
src/org/joml/Matrix2fc.java
src/org/joml/Matrix3d.java
src/org/joml/Matrix3f.java
src/org/joml/Matrix3x2d.java
src/org/joml/Matrix3x2f.java
src/org/joml/Operators.kt
src/org/joml/Vector2d.java
src/org/joml/Vector2dc.java
src/org/joml/Vector2f.java
src/org/joml/Vector2fc.java
src/org/joml/internal/MemUtil.java
test/org/joml/test/Matrix2fTest.java

This PR creates 4 new classes, `Matrix2f`, `Matrix2fc`, `Matrix2d` and `Matrix2dc`. It also adds methods to various other existing classes to additionally support the new classes, where it makes sense.
I was working off `Matrix3f` when I was doing this, for a list of features that `Matrix2f` should support. I think I got everything from there which makes sense in 2D, let me know if I missed something.

2x2 matrices (#180)

---

src/org/joml/Matrix3f.java

Fix Matrix3f.mulLocal

---

test/org/joml/test/Matrix3fTest.java
test/org/joml/test/Matrix4fTest.java

Here are some test cases for Matrix transpose that should help with covering https://github.com/JOML-CI/JOML/pull/219

added test cases for matrix transpose

---

src/org/joml/Rectangled.java
src/org/joml/Rectanglef.java
src/org/joml/Rectanglei.java

here are some methods for the width and height of a rectangle.

added rectangle width and height

---

src/org/joml/Random.java

(when you do not really care about what value does the seed hold).
In my usecases I have never meet such a situation that I have to choose a seed by myself.
In other word I think add such a constructor is useful.

add a easy way to create a Random 

---

src/org/joml/Rectanglei.java

I went back and added some more methods to fill out rectanglei some more. if these sets of functions are good then I'll go back and add them to the other rectangled and rectanglef.There are probably some details that I could correct for this. 
- size
- width
- height
- overlap
- contains
- rect
- point
- overlap
- intersect
one thing that termath has that might be useful is some of the createUtility Methods. These are a bit overkill but maybe something for location and size would be useful. 
```
public static Rect2i createFromMinAndSize(int x, int y, int width, int height) {
if (width <= 0 || height <= 0) {
return EMPTY;
}
return new Rect2i(x, y, width, height);
}
public static Rect2i createFromMinAndMax(int minX, int minY, int maxX, int maxY) {
if (maxX < minX || maxY < minY) {
return …
```

WIP: rectangle improvements

---

test/org/joml/test/TestUtil.java
test/org/joml/test/Vector2dTest.java
test/org/joml/test/Vector2fTest.java

Organized relevant sections in TestUtil. grouped assertion and equal methods
for Quaternion.

Add test cases for Vector2f/d.perpendicular()

---

src/org/joml/AABBd.java
src/org/joml/AABBf.java
src/org/joml/AABBi.java
src/org/joml/Rectangled.java
src/org/joml/Rectanglef.java
src/org/joml/Rectanglei.java
test/org/joml/test/RectangledTest.java
test/org/joml/test/RectanglefTest.java
test/org/joml/test/RectangleiTest.java

- swapped AABBi/d/f#test* -->  AABBi/d/f#intersects* 
- add AABBi/d/f#intersection
- add AABBi/d/f#isValid
- add AABBi/d/f#validate
- rename Rectanglei/d/f#intersects --> Rectanglei/d/f#intersectsRectangle
- rename Rectanglei/d/f#contains --> Rectanglei/d/f#containsPoint

Unify AABB/Rectangle intersection test method names

---

src/org/joml/GeometryUtils.java
test/org/joml/test/GeometryUtilsTest.java

also add unit tests for this case

Fix bitangent calculation in GeometryUtils

---

src/org/joml/Rectangled.java
src/org/joml/Rectanglef.java
src/org/joml/Rectanglei.java

Here are some helper operators for set. should help with consistency between AABBi/f/d and Rectanglei/f/d.

Add Rectangle.setMin/Max() and set(Rectangle)

---

src/org/joml/Quaterniond.java
src/org/joml/Quaterniondc.java
src/org/joml/Quaternionf.java
src/org/joml/Quaternionfc.java

This should match up more with equals for Vector3, Matrix4 and Matrix3.

Add Quaterntion/d/f#equals

---

test/org/joml/test/AABBiTest.java

here are some test cases for AABB that should help with resolving changes in https://github.com/JOML-CI/JOML/pull/246

Add AABBiTest for corner and edges

---

test/org/joml/test/MathTest.java

I was working on some functions for finite and needed some test to verify consistency.

add finite test for Math

---

src/org/joml/Vector2i.java
test/org/joml/test/Vector2iTest.java

here is a follow up PR that follow of changes I made in: https://github.com/JOML-CI/JOML/pull/269

add #Vector2i(float/double,float/double,RoundingMode)

---

src/org/joml/Operators.kt

I think using 'plusAssign' kotlin operate is better, because call  ' a += b ' the user will understand  that plus operate may change value of a,  but  'c = a + b' may lead to misunderstand that c is a new value,  so I implement the 'plusAssign' instead of  previous  'plus' operate

using 'plusAssign' operate instead of 'plus'

---

src/main/java/org/joml/Quaterniond.java
src/main/java/org/joml/Quaternionf.java
src/test/java/org/joml/test/QuaternionDTest.java
src/test/java/org/joml/test/QuaternionfTest.java

A sign in the calculation was incorrect.
Also added a test for this (copied from the other getEulerAngle tests).

Fix incorrect sign in Quaternion#getEulerAnglesZYX

---

src/main/java/org/joml/Math.java

Make these useful constants available externally

---

src/main/java/org/joml/AxisAngle4d.java
src/main/java/org/joml/AxisAngle4f.java
src/main/java/org/joml/Intersectiond.java
src/main/java/org/joml/Intersectionf.java
src/main/java/org/joml/Matrix4d.java
src/main/java/org/joml/Matrix4f.java
src/main/java/org/joml/Quaterniond.java
src/main/java/org/joml/Quaternionf.java
src/main/java/org/joml/sampling/Convolution.java
src/main/java/org/joml/sampling/PoissonSampling.java
src/main/java/org/joml/sampling/SpiralSampling.java
src/main/java/org/joml/sampling/StratifiedSampling.java

Optimizations:
- Math.PI + Math.PI -> Math.PI_TIMES_2
- multiply with inverse numbers instead of dividing (excl. single-use scenarios)
- move some calculations outside of loops
In the future I'm planning to do optimization with fma too, but currently i don't have the time for that.

Optimize various things
