JOML-CI/JOML

src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java

Added equals function in Vector classes as a convenience. The equals() function of an object is commonly used in the contains() function of the standard container classes  (e.g. ArrayList, List).

Implemented Object.equals() in Vector classes

---

.gitignore
src/org/joml/AngleAxis4f.java
src/org/joml/Matrix4d.java
src/org/joml/Matrix4f.java
src/org/joml/Quaternion.java
src/org/joml/QuaternionD.java
src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java

* In all Vector, Quaternion and AngleAxis classes:
* `toString()` uses a default format of "0.000E0" (scientific notation with 3 decimal places), just like in the Matrix classes
* `String toString(NumberFormat)` allows the user to specify their own format, just like in the Matrix classes
* `toString()` in the Matrix4 classes prints a newline directly at the end, so that matrices are better distinguishable (the Matrix3 classes already had this)
* Added /test/ folder to .gitignore (so unit tests don't get committed)

Added formatting options to most classes

---

.gitignore
src/org/joml/AngleAxis4f.java
src/org/joml/Quaternion.java
src/org/joml/QuaternionD.java
src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java
test/org/joml/test/TestUtil.java
test/org/joml/test/Vector2dTest.java
test/org/joml/test/Vector2fTest.java
test/org/joml/test/Vector3dTest.java
test/org/joml/test/Vector3fTest.java
test/org/joml/test/Vector4dTest.java
test/org/joml/test/Vector4fTest.java

* Added `angle` and `angleCos` methods to Vector classes. These return the angle and the cosinus of the angle, respectively, of two vectors. The angle is in radians.
* Added static `negate` methods to Vector classes.
* Removed the commas from and added whitespace to the Quaternion and AngleAxis `toString` methods (so they are consistent with the Vector and Matrix classes).
* Added `org.joml.test` package with some simple test classes. At the moment only `angle` is tested.
* The `angle` method in the Vector classes returns the angle in radians. However, I did see some methods that took degrees in their parameters. I decided to let the user choose whether they want to have it in radians or convert it to degrees. Is this correct? Which angle unit system should I use?

Vector angle calculations, basic test package

---

src/org/joml/AxisAngle4f.java
src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java

All Vector classes now have constructors accepting (ByteBuffer) and (index, ByteBuffer), methods set(ByteBuffer) and set(index, ByteBuffer), and methods get(ByteBuffer) and get(index, ByteBuffer).
All Vector float classes have their respective FloatBuffer versions while Vector double classes have their respective DoubleBuffer versions.

Added get/set methods to all Vector classes that accept ByteBuffer and Float/DoubleBuffer.

---

src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java

- All Vector's constructors and set methods take a single value to initialize all components
- Normalized all javadoc argument description to an indent of 9 spaces.
- All references to x, y, z, and w use the word component instead of value or coordinate.

Single-value constructor and set method and numerous javadoc improvements

---

.gitignore

My IDE of choice is IntelliJ IDEA. Is it fine if I add its specific files to the .gitignore? This way any others who use it that fork this library and contribute don't see its files and accidentally add them with `git add --all`

Added IntelliJ IDEA file to .gitignore.

---

src/org/joml/BaseVector2f.java
src/org/joml/ImmutableVector2f.java
src/org/joml/Vector2f.java
src/org/joml/Vector2fr.java

__Changes:__
- Extracted out the definition all non-mutating methods into an interface Vector2fr (r = readable).
- Pulled out implementation of non-mutating methods into BaseVector2f.
- Created a new ImmutableVector2f implementation of Vector2fr
- Changed methods parameters to Vector2fr where appropriate
__Notes:__
* Chose the name Vector2fr for the interface, where r nominally stands for readable or read-only. Not necessarily the best name, but is concise.
* Added an abstract base class with the common implementations. There is potentially some trade off here (depending how well Java optimises function calls) - theoretically performance may be better implementing them in the implementations so they can use the x and y variables directly rather than through their accessors. I chose to go …

Example implementation of support for immutable math types using Vector2f

---

src/org/joml/Vector4d.java
test/org/joml/test/Vector4dTest.java

Fixes an issue with Vector4d's mul(double, Vector4d) and div(double, Vector4d) - they incorrectly alter the called object rather than update the provided destination Vector4d.

Fix for incorrect div and mul methods in Vector4d

---

src/org/joml/Quaterniond.java
src/org/joml/Quaternionf.java
test/org/joml/test/QuaternionDTest.java
test/org/joml/test/QuaternionTest.java

Fixed a situation where Quaternionf#rotateTo and Quaterniond#rotateTo would return ```this``` rather than the destination Quaternion.

Fix incorrect return value from Quaternion#rotateTo

---

src/org/joml/Vector2i.java
src/org/joml/Vector3i.java
src/org/joml/Vector4i.java

Here is a basic set. Still looking at how to template the generation easily.

Adding Integer Vectors

---

src/org/joml/Intersectiond.java
src/org/joml/Intersectionf.java

In the classes Intersectionf and Intersectiond, some functions (namely `intersectSphereSphere` and `intersectCircleCircle`) were forwarding the wrong squared radius (Radius squared of circle/sphere B instead of circle/sphere A).

Fixed issue with squared radius in Intersectionf/Intersectiond 

---

src/org/joml/Vector2d.java
src/org/joml/Vector2f.java
src/org/joml/Vector2i.java
src/org/joml/Vector3d.java
src/org/joml/Vector3f.java
src/org/joml/Vector3i.java
src/org/joml/Vector4d.java
src/org/joml/Vector4f.java
src/org/joml/Vector4i.java

In Vector3f and Vector3d there is already a method to set the value of a component by an index, e.g. in Vector3f: `public Vector3f set(int component, float value)`
But is was missing in the other vector classes, so i think it should be in every vector class for more consistency.
Problem is that in Vector2i there is already a mthod `set(int, int)` that has another purpose, that is why another method name was needed ->setComponent.

Add the setComponent(component, value) method to all vector classes

---

src/org/joml/Extensions.kt

I saw a file of operators and decided that it would be convenient to use such extensions when using vectors and matrices in Kotlin. I also added get methods without arguments that return new instances of objects. If it's bad, I should remove them.

Kotlin get/set extensions for (Byte/Float/Double/Int)Buffer 

---

pom.xml

The OSGi specification defines the "comma" as separator for package export entries.
Currently, a blank is used which results in corrupted OSGI metadata and hence
JOML can not be used in an OSGi environment (no package is exported).

Fix Export-Package of the OSGi metadata.

---

src/org/joml/Matrix4d.java
src/org/joml/Matrix4f.java

Resolves #218 , fixing a nasty calculation error in 4x4 transposes.

Correct element caching in Matrix4.transposeGeneric

---

src/org/joml/Rectangled.java
src/org/joml/Rectanglef.java
src/org/joml/Rectanglei.java
test/org/joml/test/RectangleScaleTest.java

As the title suggests, I found that when working on a project I needed to manipulate the bounds of a rectangle, so I thought this would be a neat addition to the library.
Now, given that this is actually my first contribution to an open source project, I have a feeling that I may not have done it entirely correctly. I read through the contribution guidelines but there are a few questions I still have, if I may ask here,
- Should I have created a separate branch for the feature or would the master branch be fine?
- I added the feature on a Windows machine, so when I went to test it, maven's checkstyle plugin kept complaining of the CRLF line endings. I was wondering if that would be an issue?
Thank you

Add scaling functions to Rectangle* classes

---

src/org/joml/Matrix4f.java

There's no reason as to why this method needs to take a Vector3f, and not a Vector3fc.

Make Matrix4f.rotateXYZ able to take a Vector3fc

---

test/org/joml/test/RectangledTest.java
test/org/joml/test/RectanglefTest.java
test/org/joml/test/RectangleiTest.java

Here are some tests cases I wrote up for rectangle. This should help with a bit of code coverage for `rectanglei`, `rectanglef` and `rectangled`.  I might have a couple other tweaks here and there but I really like this library so far.

added test cases for rectangle

---

src/org/joml/Vector2d.java
src/org/joml/Vector2f.java

the calculation for y used the new value of x

Fix perpendicular caluclations of Vector2f and Vector2d

---

src/org/joml/Quaterniond.java
src/org/joml/Quaternionf.java

This PR fixes the parameter ordering of the `rotateYXZ()` method in the Quaternion classes.

Fix parameter ordering in Quaternion#rotateYXZ

---

src/org/joml/AABBd.java
src/org/joml/AABBf.java
src/org/joml/AABBi.java

I added a set function for each AABB so they can be set from a source AABB without declaring a new AABB.

add AABBi/d/f#set(AABBi/d/f source)

---

src/org/joml/Vector2i.java
src/org/joml/Vector2ic.java

Adds methods to perform division that are present on Vector3i and Vector4i, but were missing on Vector2i

Add Vector2i.div()

---

src/org/joml/AABBd.java
src/org/joml/AABBdc.java
src/org/joml/AABBf.java
src/org/joml/AABBfc.java
src/org/joml/AABBi.java
src/org/joml/AABBic.java

Here is a read-only interface for AABB. I have some methods with an AABB I would like to expose but would prefer if it was not possible to modify. Here is an implementation that is similar to Vectror*c type interfaces. I would like to also do this for Circle/Ray/Sphere.

Add read-only interface AABBdi/f/d

---

src/org/joml/GeometryUtils.java

There is a typo in one of the cases:
(z,0,x) is not perpendicular to (x,y,z), but
(-z,0,x) is.

Fix sign error in GeometryUtils.perpendicular()

---

src/org/joml/Vector3i.java
test/org/joml/test/Vector3iTest.java

I noticed that Vector3i(Vector2dc,float/double z) only modifies the local value and does not apply those value to Vector3i. I also added new Vector3i(float/double, mode). 
```
Vector3i v1 = new Vector3i(0.0f,.6f,.7f, RoundingMode.FLOOR);
Vector3i v3 = new Vector3i(new Vector3f(9.5f,1.6f,5.0f), RoundingMode.FLOOR);
Vector3i v4 = new Vector3i(new Vector2d(9.5f,1.6f),5.0f, RoundingMode.FLOOR);
```

Add Vector3i(float/double x,y,z) and test case

---

src/org/joml/Math.java

Here are some lerp methods that should fit in Math.java. I think I should expand out the methods used in bilerp and trilerp at the cost of readability.

add lerp methods to Math

---

test/org/joml/test/Vector3iTest.java

Here are some trivial test cases for Vector3i that should improve code coverage. There should be a lot more test cases for operations where there are self operations i.e v1 add v1 or v1 sub v1. I know I've caught bugs where this has been a problem.

add test for Vector3i

---

src/org/joml/Matrix3dc.java

The corresponding parameter in the implement class 'Matrix3d' is  'int row, int  column'
It may make confuse when call 'Matrix3dc.getRowColumn()' method.

fix method parameter signature define different

---

src/org/joml/Matrix4x3d.java

the 'index' parameter is never used

Fix Matrix4x3d.setFloats(index, ByteBuffer)

---

src/main/java/org/joml/package.html

Before:
It's different from the IDE background.

Remove background color in package.html

---

src/main/java/org/joml/Math.java

Basically replace x * y + z with fma(x, y, z).
Should be about 35-45% faster on an Intel processor.
Proof of concept:
JMH benchmark code:
```java
package org.example;
import org.openjdk.jmh.annotations.*;
import java.io.IOException;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.TimeUnit;
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 2, time = 1000, timeUnit = TimeUnit.MILLISECONDS)
@Measurement(iterations = 4, time = 2500, timeUnit = TimeUnit.MILLISECONDS)
@BenchmarkMode(Mode.AverageTime)
@Fork(1)
public class Main {
public static void main(String[] args) throws IOException {
org.openjdk.jmh.Main.main(args);
}
@State(Scope.Benchmark)
public static class BenchState {
public double value;
@Setup(Level.Trial)
public void setUp() {
value = …
```

Optimize fastAtan2

---

src/main/java/org/joml/Matrix2d.java
src/main/java/org/joml/Matrix2f.java
src/main/java/org/joml/Matrix3x2d.java
src/main/java/org/joml/Matrix3x2f.java
src/main/java/org/joml/Matrix4f.java
src/main/java/org/joml/Matrix4x3f.java
src/main/java/org/joml/MemUtil.java

All of the underlying `MemUtil` functions for copying rely on the read-only interface methods. These now specify the read-only class in their parameters. This should allow for greater flexibility in using these memory helpers.

Change `Matrix4f.set3x3(Matrix4f)` to `Matrix4f.set3x3(Matrix4fc)`

---

build.gradle

Import kotlin-stdlib as a compileOnly dependency.
This prevents it from being exposed in published Maven or Gradle metadata.
Closes #352

Exclude Kotlin stdlib from published Gradle metadata
